name: ESLint Check

on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
    branches:
      - master
    paths:
      - "front/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_JS_VERSION: "20.15.1"

jobs:
  lint:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - uses: actions/setup-node@v4
        with:
          node-version: "20.15.1"
          cache-dependency-path: frontend/package-lock.lock

      - name: eslint review setting
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          eslint_flags: "front/**/*.{ts,tsx}"
          fail_on_error: true

      - name: eslint check
        run: |
          cd front 
          rm -rf node_modules
          npm install
          npm run lint
